// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sFqKXDN8rHnCDU91Y9JUYu
// Component: uTgmpuxKs5v_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: SfWv_--dQ9Pb/component
import BackersLink from "../../BackersLink"; // plasmic-import: Sl58UbzqihgE/component
import TeamItem from "../../TeamItem"; // plasmic-import: 1D1vYwMlm3FT/component
import Button3 from "../../Button3"; // plasmic-import: 6mO-YzPwqb-d/component
import Footer from "../../Footer"; // plasmic-import: irj0wRv4NhUG/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_friends_tech_king.module.css"; // plasmic-import: sFqKXDN8rHnCDU91Y9JUYu/projectcss
import sty from "./PlasmicAbout.module.css"; // plasmic-import: uTgmpuxKs5v_/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: e58rgm-WFTW/icon
import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: uC8bBJhPRpth/icon

createPlasmicElementProxy;

export type PlasmicAbout__VariantMembers = {};
export type PlasmicAbout__VariantsArgs = {};
type VariantPropType = keyof PlasmicAbout__VariantsArgs;
export const PlasmicAbout__VariantProps = new Array<VariantPropType>();

export type PlasmicAbout__ArgsType = {};
type ArgPropType = keyof PlasmicAbout__ArgsType;
export const PlasmicAbout__ArgProps = new Array<ArgPropType>();

export type PlasmicAbout__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  button3?: p.Flex<typeof Button3>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultAboutProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAbout__RenderFunc(props: {
  variants: PlasmicAbout__VariantsArgs;
  args: PlasmicAbout__ArgsType;
  overrides: PlasmicAbout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__p6N6Z)}>
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__slSVw)}>
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__iyTxS
                )}
              >
                {"About friend.tech"}
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ibGe1
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      fontWeight: 700,
                      color: "#2D2D2D",
                      fontStyle: "italic"
                    }}
                  >
                    {
                      "\u201cIn our daily life, we all still need traditional financial services, but we do not want to miss out on opportunities opened by modern finance. Our Future is \u201cWeb3 banking\u201d that connects the old world with the new, offering enhanced and secure services for anyone with a smartphone. Welcome to friend.tech, your guide to the Web 3 Finance!\u201d"
                    }
                  </span>
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___14EHj)}>
                <div className={classNames(projectcss.all, sty.freeBox__zXHh)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___081Zp)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100px"}
                    loading={"lazy"}
                    src={
                      "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/5ce13a7524b02e03775131f9_ceo-avatar.jpg"
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__eGxv5)}>
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__pm8Vh
                    )}
                  >
                    {"Alaksandar Daminik"}
                  </h6>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kijGn
                    )}
                  >
                    {
                      "CEO friend.tech, CVA Board Member and Innovaud Ambassador"
                    }
                  </div>
                </div>
              </div>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ysKOc)}
              >
                <BackersLink
                  className={classNames("__wab_instance", sty.backersLink__auA)}
                />

                <BackersLink
                  className={classNames(
                    "__wab_instance",
                    sty.backersLink__pLay
                  )}
                  slot={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__misNg)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/63c05fb0cdaada6a20231e71_testimonial_ledger.svg"
                      }
                    />
                  }
                >
                  {"Custody secured by Ledger Enterprise"}
                </BackersLink>
                <BackersLink
                  className={classNames(
                    "__wab_instance",
                    sty.backersLink___5UbNm
                  )}
                  slot={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__qoVe)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/63c05fb35925bbf0b0b93c0a_testimonial_torino_fc.svg"
                      }
                    />
                  }
                >
                  {"Official Crypto Partner of Torino FC"}
                </BackersLink>
              </p.Stack>
              <div className={classNames(projectcss.all, sty.freeBox___0V2Qt)}>
                <h5
                  className={classNames(
                    projectcss.all,
                    projectcss.h5,
                    projectcss.__wab_text,
                    sty.h5__jqlTp
                  )}
                >
                  {"Memberships"}
                </h5>
                <div className={classNames(projectcss.all, sty.freeBox__bmqAa)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zuJsh)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zZXnG)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mgLqB)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/friends_tech_king/images/image3.png",
                          fullWidth: 250,
                          fullHeight: 51,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__p80E8
                      )}
                    >
                      {
                        "friend.tech is affiliated with Financial Services Ombudsman FINSOM."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sjbPz)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xyKo3)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__oiOei)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/friends_tech_king/images/image4.png",
                          fullWidth: 490,
                          fullHeight: 96,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pWt6B
                      )}
                    >
                      {
                        "The world\u2019s leading blockchain and cryptographic technologies ecosystem."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___0SfAo)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pu7Dp)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__sW7Lx)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/friends_tech_king/images/image5.png",
                          fullWidth: 445,
                          fullHeight: 57,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lUvi6
                      )}
                    >
                      {
                        "The innovation and investment promotion agency for the canton of Vaud, Switzerland"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kf7Yt)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hycY)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__q91Us)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/friends_tech_king/images/image2.png",
                          fullWidth: 360,
                          fullHeight: 73,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__an4Ye
                      )}
                    >
                      {
                        "Professionals in the digital asset and blockchain sector throughout France and Europe."
                      }
                    </div>
                  </div>
                </div>
              </div>
              <section
                className={classNames(projectcss.all, sty.section___55Lkw)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__ncGal
                  )}
                >
                  {"About the Company"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e8Lsh
                  )}
                >
                  {
                    "friend.tech - a multi-faced FinTech platform providing a variety of Web3 crypto services. friend.tech's caters to active HODLers, allowing them to use their digital assets beyond hodling and trading.\n\nfriend.tech supports all major crypto currencies and tokens (BTC, ETH, LTC, XLM, XRP, BNB, USDT, USDC, TUSD, PAXG, DAI, etc).\n\nfriend.tech offer integrated crypto exchange, trading, lending and crypto-rewards services.\n\nUser's digital assets are safely guarded with a State of the Art Ledger Vault's advanced custody and Fireblocks security options. Non-custodial Web 3 wallet will to be integrated to the friend.tech App early 2024.\n\nfriend.tech is an EU and Swiss-based brand with regulated institutions in Switzerland, Italy and other EU countries.\n\nfriend.tech is an active member of the Crypto Valley Association.\n\nfriend.tech Team has strong and unique expertise in Commercial Finance, FX/CFD trading, creation of e-commerce and e-learning platforms, Blockchain and Distributed Ledger Technology.\n\nOur team combines the wisdom and practices from the world of traditional finance with the start-up spirit of Digital industry."
                  }
                </div>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__rv8C)}
                >
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__reuWp
                    )}
                  >
                    {
                      "\u201cOur future is in Web3 banking\u201d \u2013 friend.tech CEO"
                    }
                  </h5>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gOHxl
                    )}
                  >
                    {
                      "Web3 banking is being built as we speak. friend.tech is a front-runner in this new financial evolution. But what does Web3 banking look like exactly? CEO Alaksandar Daminik sits down with us to explain."
                    }
                  </div>
                </p.Stack>
              </section>
              <section
                className={classNames(projectcss.all, sty.section__f2NsW)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__tbKe
                  )}
                >
                  {"Our Mission"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nsKdY
                  )}
                >
                  {"friend.tech is your guide to the Web3 world."}
                </div>
                <h5
                  className={classNames(
                    projectcss.all,
                    projectcss.h5,
                    projectcss.__wab_text,
                    sty.h5__nle3K
                  )}
                >
                  {
                    "We make your digital assets work for you by building bridges between Traditional finance and crypto; Banking and Trading; CeFi and DeFi."
                  }
                </h5>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q54KQ
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Trading solutions"}
                    </span>
                    <React.Fragment>
                      {
                        " unlock an opportunity to benefit from market movements and multiply your digital assets.\n\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Crypto-backed loans"}
                    </span>
                    <React.Fragment>
                      {
                        " helps one get cash for regular needs and keep hodling at the same time.\n\nOn top of that our "
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Reward programs"}
                    </span>
                    <React.Fragment>
                      {
                        " are built to make your Web3 journey interesting and engaging."
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </section>
              <section
                className={classNames(projectcss.all, sty.section__owSpL)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__z3M5B
                  )}
                >
                  {"Team Experience"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nlkEs
                  )}
                >
                  {
                    "Ask us something if you\u2019d like to learn more about our products & services"
                  }
                </div>
                <TeamItem
                  className={classNames("__wab_instance", sty.teamItem__jNdXj)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wyfA7)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100px"}
                    loading={"lazy"}
                    src={
                      "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/61caee021996d9706c2de56b_ilya-p-500.jpeg"
                    }
                  />
                </TeamItem>
                <TeamItem
                  className={classNames("__wab_instance", sty.teamItem___95NCy)}
                  slot={
                    <React.Fragment>
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__uqAV
                        )}
                      >
                        {"Alex Vinny "}
                      </h6>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gX8TN
                        )}
                      >
                        {"HEAD OF PRODUCT"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2YqW
                        )}
                      >
                        {
                          "Financial Apps expert. Former Senior UI/UX engineer of one of the leading trading Apps\nwith 2.2 M clients across 110 countries."
                        }
                      </div>
                    </React.Fragment>
                  }
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__pKo0A)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100px"}
                    loading={"lazy"}
                    src={
                      "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/61caee029a14f64183e19cbd_alex-p-500.jpeg"
                    }
                  />
                </TeamItem>
                <TeamItem
                  className={classNames("__wab_instance", sty.teamItem__ns3JZ)}
                  slot={
                    <React.Fragment>
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__tk0T
                        )}
                      >
                        {"Natalia Romanova \u200d"}
                      </h6>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xW7Ya
                        )}
                      >
                        {"EXEC. DIRECTOR"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jqb80
                        )}
                      >
                        {
                          "Experience in Accounting including commercial finance, cross-border transactions. Fully qualified accountant with specialization in financial management."
                        }
                      </div>
                    </React.Fragment>
                  }
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__p1L6P)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100px"}
                    loading={"lazy"}
                    src={
                      "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/61caee0244880580afdeb1e3_natalia-p-500.jpeg"
                    }
                  />
                </TeamItem>
                <TeamItem
                  className={classNames("__wab_instance", sty.teamItem__jEhxq)}
                  slot={
                    <React.Fragment>
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__av0Zf
                        )}
                      >
                        {"Igor Bannikov "}
                      </h6>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vMr7
                        )}
                      >
                        {"CRO"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rg7Jr
                        )}
                      >
                        {
                          "Senior professional with experience of Compliance and Risk management within reputable Swiss Bank.Expert in compliance and regulations of investment and private banks."
                        }
                      </div>
                    </React.Fragment>
                  }
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__olufa)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100px"}
                    loading={"lazy"}
                    src={
                      "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/61caee00663724200cfe63d3_igor-p-500.jpeg"
                    }
                  />
                </TeamItem>
              </section>
              <section
                className={classNames(projectcss.all, sty.section__ivYK)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__aGqYs
                  )}
                >
                  {"Our Partners"}
                </h3>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__f4Yf4)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__i8Bc)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fxB)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___0ZnQm)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={
                          "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/61d83f692586c50155984c57_ledger-entreprise-solutions-logo-blue.svg"
                        }
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qvjbt
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"Secured custody."}
                        </span>
                        <React.Fragment>
                          {
                            " Custody management solution and $150 million pooled crime insurance."
                          }
                        </React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mggvD)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vfOxK)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jQeVr)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={
                          "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/63c14ba144d4cf7d4defdd8a_Magic-Square-New-Logo-Light-Backgrounds.svg"
                        }
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___60I79
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"Web 3.0 Games and Apps. "}
                        </span>
                        <React.Fragment>
                          {
                            "Discover Community-Vetted Blockchain and Crypto Apps, Games, CeDeFi and more"
                          }
                        </React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cOcQ)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qrK7)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__enb6G)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={
                          "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/61cbdeed39f4004c58c2736d_fireblocks-logo.jpg"
                        }
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gxdOz
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"Asset Platform."}
                        </span>
                        <React.Fragment>
                          {
                            " Hundreds of crypto and digital asset businesses use Fireblocks software and APIs to custody."
                          }
                        </React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                </p.Stack>
              </section>
              <section
                className={classNames(projectcss.all, sty.section__iMtPq)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__bhenz
                  )}
                >
                  {"Why You Choose friend.tech"}
                </h3>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__eoVtZ)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___2CRlj)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__vw0ET)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__byj38)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={
                          "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/5da8d257dae2a4e2440cd59c_security.svg"
                        }
                      />

                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___6Z0Rk
                        )}
                      >
                        {"Secured crypto wallet"}
                      </h5>
                    </p.Stack>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yDgGs
                      )}
                    >
                      {
                        "friend.tech uses Ledger Vault's industry leading information technology infrastructure to securely control its crypto assets. Ledger Vault provides security solutions and $150M pooled crime insurance."
                      }
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__itazX)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__f8VJ)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__dVHs)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={
                          "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/5da8d258cbc040c25a538123_safety.svg"
                        }
                      />

                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__fN4Od
                        )}
                      >
                        {"Safety of fiat funds"}
                      </h5>
                    </p.Stack>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iok1M
                      )}
                    >
                      {
                        "friend.tech has its bank accounts at reputable banks at Europe and Switzerland, We do not avoid banks. We partner with them."
                      }
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lggyF)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__jsv5C)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__p3U1)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={
                          "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/5da8d257e2439620ab3e210a_team.svg"
                        }
                      />

                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__pfrJ4
                        )}
                      >
                        {"Team experience"}
                      </h5>
                    </p.Stack>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ij7R
                      )}
                    >
                      {
                        "friend.tech management and engineering teams have 15+ years in FinTech and technology development. We're not an ICO backed!"
                      }
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jPvP)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9OfHr
                      )}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___5I5Pg)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={
                          "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/5d65135dca4f1a3669bf0aee_ftp.svg"
                        }
                      />

                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___00Fq2
                        )}
                      >
                        {"Risk control"}
                      </h5>
                    </p.Stack>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aiyot
                      )}
                    >
                      {
                        "friend.tech team has extensive expertise in currency exchange risk management. We know how to save our funds so we know how to save yours."
                      }
                    </div>
                  </p.Stack>
                </p.Stack>
              </section>
              <section
                className={classNames(projectcss.all, sty.section__dPnZu)}
              >
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___6YwQe
                  )}
                >
                  {"Safety and Security"}
                </h4>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8J2OX
                  )}
                >
                  {
                    "All operations at friend.tech are 100% secure. friend.tech follows all the industry best practices for IT security checks, data protection, access rights, and data encryption.\n\nfriend.tech uses Ledger Vault's industry leading information technology infrastructure to securely control its crypto assets with a multi-authorization self-custody management solution and $150 million pooled crime insurance."
                  }
                </div>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___2Qwpk)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ldJ)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/friends_tech_king/images/image2.png",
                      fullWidth: 360,
                      fullHeight: 73,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__tXnIu)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/friends_tech_king/images/image3.png",
                      fullWidth: 250,
                      fullHeight: 51,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___0G7Qx)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/friends_tech_king/images/image4.png",
                      fullWidth: 490,
                      fullHeight: 96,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cg0Jn)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/friends_tech_king/images/image5.png",
                      fullWidth: 445,
                      fullHeight: 57,
                      aspectRatio: undefined
                    }}
                  />
                </p.Stack>
              </section>
              <section
                className={classNames(projectcss.all, sty.section__q7F3Z)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__eWjSh)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___3O6D)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/63c825b85881a9fcf1edb652_screen_cta_2-p-800.png"
                    }
                  />
                </div>
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__vMj1S
                  )}
                >
                  {"Get Instant Crypto Loans"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xEYhm
                  )}
                >
                  {
                    "Store, exchange stablecoins and crypto. Rewards, staking and loans integrated. "
                  }
                </div>
                <Button3
                  data-plasmic-name={"button3"}
                  data-plasmic-override={overrides.button3}
                  className={classNames("__wab_instance", sty.button3)}
                  color={"white"}
                  link={`/loan`}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lbku8
                    )}
                  >
                    {"Get Loan"}
                  </div>
                </Button3>
              </section>
              <section
                className={classNames(projectcss.all, sty.section__ypEp9)}
              >
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6__sztNk
                  )}
                >
                  {"\nFRIEND.TECH IS REGULATED IN SWITZERLAND AND EU\n"}
                </h6>
                <BackersLink
                  className={classNames(
                    "__wab_instance",
                    sty.backersLink__aWdlr
                  )}
                  slot={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rc3P5)}
                      displayHeight={"20px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"20px"}
                      loading={"lazy"}
                      src={
                        "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/5d81e319d805196b051acc75_switzerland%20(1).svg"
                      }
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pswSj
                    )}
                  >
                    {"friend.tech Regulated Financial  Control."}
                  </div>
                </BackersLink>
                <BackersLink
                  className={classNames(
                    "__wab_instance",
                    sty.backersLink___3OF6
                  )}
                  slot={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__nDOc5)}
                      displayHeight={"20px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"20px"}
                      loading={"lazy"}
                      src={
                        "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/5d81e344072bc3cc6157f8c7_european-union.svg"
                      }
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a9Mex
                    )}
                  >
                    {"friend.tech S.R.L. OAM Registration"}
                  </div>
                </BackersLink>
                <BackersLink
                  className={classNames(
                    "__wab_instance",
                    sty.backersLink__oqBim
                  )}
                  slot={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__sedkK)}
                      displayHeight={"20px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"20px"}
                      loading={"lazy"}
                      src={
                        "https://assets-global.website-files.com/5cc19fbd198b8d31a9c64876/63c1a1e8c740e1e785d20c56_wallet.svg"
                      }
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__on0M8
                    )}
                  >
                    {"Partnership with regulated EU financial providers"}
                  </div>
                </BackersLink>
              </section>
            </div>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navbar", "button3", "footer"],
  navbar: ["navbar"],
  button3: ["button3"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  button3: typeof Button3;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAbout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAbout__VariantsArgs;
    args?: PlasmicAbout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAbout__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAbout__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAbout__ArgProps,
          internalVariantPropNames: PlasmicAbout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAbout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAbout";
  } else {
    func.displayName = `PlasmicAbout.${nodeName}`;
  }
  return func;
}

export const PlasmicAbout = Object.assign(
  // Top-level PlasmicAbout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    button3: makeNodeComponent("button3"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicAbout
    internalVariantProps: PlasmicAbout__VariantProps,
    internalArgProps: PlasmicAbout__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAbout;
/* prettier-ignore-end */
